In [7]:
import numpy as np
import pandas as pd

In [8]:
df_label = pd.read_csv('qaplib_labels.txt', sep=' ', header=None, skiprows=1,
                 names=['instance', 'obj_label'])
# sort by instance name
df_label = df_label.sort_values(by="instance")
df_label.head()

  instance  obj_label
0   bur26a  5426670.0
1   bur26b  3817852.0
2   bur26c  5426795.0
3   bur26d  3821225.0
4   bur26e  5386879.0

In [9]:
# read txt
seeds = [0, 42, 47, 1111, 1234]
file_name = "results/qaplib_{}.txt"

file_names = [file_name.format(seed) for seed in seeds]
file_names

['results/qaplib_0.txt',
 'results/qaplib_42.txt',
 'results/qaplib_47.txt',
 'results/qaplib_1111.txt',
 'results/qaplib_1234.txt']

In [10]:
data = []
for file_name in file_names:
    df = pd.read_csv(file_name, sep=" ", header=None, skiprows=1)
    df.columns = ["instance", "time1", "time", "incumbent"]
    df = df[["instance", "time", "incumbent"]]
    # sort by instance name
    df = df.sort_values(by="instance")
    df['gap'] = (df["incumbent"] - df_label["obj_label"]) / df_label["obj_label"] * 100
    data.append(df)
    
df = data[0]
for d in data[1:]:
    df["time"] += d["time"]
    df["incumbent"] += d["incumbent"]
    df["gap"] += d["gap"]
df["time"] /= len(data)
df["incumbent"] /= len(data)
df["gap"] /= len(data)

In [11]:
df

    instance     time  incumbent       gap
0     bur26a    1.648  5427865.4  0.022028
1     bur26b    1.648  3818382.4  0.013893
2     bur26c    1.642  5427025.4  0.004246
3     bur26d    1.640  3821329.4  0.002732
4     bur26e    1.640  5387518.4  0.011870
..       ...      ...        ...       ...
131   tho150  113.404  8202838.8  0.853774
132    tho30    1.910   149959.2  0.015473
133    tho40    3.408   240774.0  0.107269
134   wil100   44.676   273928.4  0.326108
135    wil50    6.238    48871.6  0.113897

[136 rows x 4 columns]

In [12]:
# groupy by instance with the first 3 letters the same, then average

df_tmp = df[['instance', 'time', 'gap']]
df_tmp['group'] = df['instance'].str[:3]
grouped = df_tmp.groupby('group').agg({
    'time': 'mean',
    'gap': 'mean'
}).reset_index()

grouped

   group       time       gap
0    bur   1.646500  0.014166
1    chr   1.288000  2.311669
2    els   1.350000  0.552964
3    esc   5.990211  0.000000
4    had   1.256800  0.000000
5    kra   1.998667  0.000000
6    lip  13.189875  0.307523
7    nug   1.433333  0.005599
8    rou   1.228667  0.014426
9    scr   1.225333  0.004362
10   sko  29.650769  0.403770
11   ste   2.878000  0.336348
12   tai  18.924286  0.772201
13   tho  39.574000  0.325505
14   wil  25.457000  0.220003