In [48]:
import numpy as np
import pandas as pd

In [49]:
df_label = pd.read_csv('qaplib_labels.txt', sep=' ', header=None, skiprows=1,
                 names=['instance', 'obj_label'])
# sort by instance name
df_label = df_label.sort_values(by="instance")
df_label.head()

  instance  obj_label
0   bur26a  5426670.0
1   bur26b  3817852.0
2   bur26c  5426795.0
3   bur26d  3821225.0
4   bur26e  5386879.0

In [50]:
# read txt
seeds = [0, 42, 47, 1111, 1234]
file_name = "results/qaplib_{}.txt"

file_names = [file_name.format(seed) for seed in seeds]
file_names

['results/qaplib_0.txt',
 'results/qaplib_42.txt',
 'results/qaplib_47.txt',
 'results/qaplib_1111.txt',
 'results/qaplib_1234.txt']

In [51]:
data = []
for file_name in file_names:
    df = pd.read_csv(file_name, sep=" ", header=None, skiprows=1)
    df.columns = ["instance", "time1", "time", "incumbent"]
    df = df[["instance", "time", "incumbent"]]
    # sort by instance name
    df = df.sort_values(by="instance")
    df['gap'] = (df["incumbent"] - df_label["obj_label"]) / df_label["obj_label"] * 100
    data.append(df)
    
df = data[0]
for d in data[1:]:
    df["time"] += d["time"]
    df["incumbent"] += d["incumbent"]
    df["gap"] += d["gap"]
df["time"] /= len(data)
df["incumbent"] /= len(data)
df["gap"] /= len(data)

In [52]:
df

    instance     time  incumbent       gap
0     bur26a    1.648  5427865.4  0.022028
1     bur26b    1.648  3818382.4  0.013893
2     bur26c    1.642  5427025.4  0.004246
3     bur26d    1.640  3821329.4  0.002732
4     bur26e    1.640  5387518.4  0.011870
..       ...      ...        ...       ...
130   tho150  113.404  8202838.8  0.853774
131    tho30    1.910   149959.2  0.015473
132    tho40    3.408   240774.0  0.107269
133   wil100   44.676   273928.4  0.326108
134    wil50    6.238    48871.6  0.113897

[135 rows x 4 columns]

In [53]:
# groupy by instance with the first 3 letters the same, then average

df_tmp = df[['instance', 'time', 'gap']]
df_tmp['group'] = df['instance'].str[:3]
grouped = df_tmp.groupby('group').agg({
    'time': 'mean',
    'gap': 'mean'
}).reset_index()


# round time to 1 decimal and gap to 2 decimals in percent
grouped['time'] = grouped['time'].round(2)
grouped['gap'] = grouped['gap'].round(1)
grouped['gap'] = grouped['gap'].astype(str) + '\%'


# save to latex table
# grouped.to_latex('qaplib_results_table.tex', index=False, float_format="%.1f")
grouped.to_csv(f'qaplibs_results_table.txt', index=False, float_format="%.2f")

In [54]:
grouped

   group   time    gap
0    bur   1.65  0.0\%
1    chr   1.29  2.3\%
2    els   1.35  0.6\%
3    esc   6.26  0.0\%
4    had   1.26  0.0\%
5    kra   2.00  0.0\%
6    lip  13.19  0.3\%
7    nug   1.43  0.0\%
8    rou   1.23  0.0\%
9    scr   1.23  0.0\%
10   sko  29.65  0.4\%
11   ste   2.88  0.3\%
12   tai  18.92  0.8\%
13   tho  39.57  0.3\%
14   wil  25.46  0.2\%

In [55]:
method = "gurobi"
df = pd.read_csv(f"/home/xjx/A-xjx/QAPs/results/pygm/{method}.txt", sep=' ', header=None, skiprows=1,
                 names=['instance', 'time', 'incumbent'])
# sort by instance name
df = df.sort_values(by="instance")
df['gap'] = (df["incumbent"] - df_label["obj_label"]) / df_label["obj_label"] * 100
# drop nan rows
print(len(df))
df = df.dropna()
print(len(df))
df_tmp = df[['instance', 'time', 'gap']]
df_tmp['group'] = df['instance'].str[:3]
grouped = df_tmp.groupby('group').agg({
    'time': 'mean',
    'gap': 'mean'
}).reset_index()


# round time to 1 decimal and gap to 2 decimals in percent
grouped['time'] = grouped['time'].round(2)
grouped['gap'] = grouped['gap'].round(1)
grouped['gap'] = grouped['gap'].astype(str) + '\%'

# print latex table
# grouped.to_latex(f'pygm_{method}_results_table.tex', index=False, float_format="%.2f")
grouped.to_csv(f'pygm_{method}_results_table.txt', index=False, float_format="%.2f")

135
134

In [56]:
df

    instance    time  incumbent        gap
0     bur26a  100.02  5439428.0   0.235098
1     bur26b  100.26  3829261.0   0.298833
2     bur26c  100.02  5461476.0   0.639070
3     bur26d  100.01  3824467.0   0.084842
4     bur26e  100.04  5400355.0   0.250163
..       ...     ...        ...        ...
130   tho150  121.08  9851230.0  21.120717
131    tho30  100.01   159586.0   6.436079
132    tho40  100.01   253014.0   5.196328
133   wil100  104.30   300794.0  10.165618
134    wil50  100.09    51194.0   4.871354

[134 rows x 4 columns]